package ab.tjl.dianping.dal;

import ab.tjl.dianping.model.ShopModel;

import java.util.List;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    int insert(ShopModel record);

    /**
     * 查找所有门店
     * @return
     */
    List<ShopModel> selectAll();

    /**
     * 统计所有门店
     * @return
     */
    Integer countAllShop();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    ShopModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Feb 07 19:12:22 CST 2020
     */
    int updateByPrimaryKey(ShopModel record);
}